# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import robot_control_pb2 as robot__control__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in robot_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotTeleopServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TeleopSession = channel.stream_stream(
                '/robotcontrol.RobotTeleopService/TeleopSession',
                request_serializer=robot__control__pb2.MasterCommand.SerializeToString,
                response_deserializer=robot__control__pb2.SlaveState.FromString,
                _registered_method=True)


class RobotTeleopServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TeleopSession(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotTeleopServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TeleopSession': grpc.stream_stream_rpc_method_handler(
                    servicer.TeleopSession,
                    request_deserializer=robot__control__pb2.MasterCommand.FromString,
                    response_serializer=robot__control__pb2.SlaveState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robotcontrol.RobotTeleopService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robotcontrol.RobotTeleopService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotTeleopService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TeleopSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/robotcontrol.RobotTeleopService/TeleopSession',
            robot__control__pb2.MasterCommand.SerializeToString,
            robot__control__pb2.SlaveState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
