# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot_control.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'robot_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13robot_control.proto\x12\x0crobotcontrol\"\xa9\x01\n\rMasterCommand\x12\x15\n\rteleop_enable\x18\x01 \x01(\x08\x12/\n\x0c\x63ontrol_mode\x18\x02 \x01(\x0e\x32\x19.robotcontrol.ControlMode\x12*\n\x06joints\x18\x03 \x01(\x0b\x32\x1a.robotcontrol.JointCommand\x12\x14\n\x0ctimestamp_ns\x18\x04 \x01(\x04\x12\x0e\n\x06seq_id\x18\x05 \x01(\r\"B\n\x0cJointCommand\x12\x10\n\x08position\x18\x01 \x03(\x01\x12\x10\n\x08velocity\x18\x02 \x03(\x01\x12\x0e\n\x06torque\x18\x03 \x03(\x01\"\x8e\x01\n\nSlaveState\x12(\n\x06joints\x18\x01 \x01(\x0b\x32\x18.robotcontrol.JointState\x12\x15\n\rteleop_active\x18\x02 \x01(\x08\x12)\n\x06status\x18\x03 \x01(\x0e\x32\x19.robotcontrol.SlaveStatus\x12\x14\n\x0ctimestamp_ns\x18\x04 \x01(\x04\"@\n\nJointState\x12\x10\n\x08position\x18\x01 \x03(\x01\x12\x10\n\x08velocity\x18\x02 \x03(\x01\x12\x0e\n\x06torque\x18\x03 \x03(\x01*S\n\x0b\x43ontrolMode\x12\x1c\n\x18\x43ONTROL_MODE_UNSPECIFIED\x10\x00\x12\x0c\n\x08POSITION\x10\x01\x12\x0c\n\x08VELOCITY\x10\x02\x12\n\n\x06TORQUE\x10\x03*I\n\x0bSlaveStatus\x12\x1c\n\x18SLAVE_STATUS_UNSPECIFIED\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\t\n\x05\x45STOP\x10\x03\x32`\n\x12RobotTeleopService\x12J\n\rTeleopSession\x12\x1b.robotcontrol.MasterCommand\x1a\x18.robotcontrol.SlaveState(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTROLMODE']._serialized_start=488
  _globals['_CONTROLMODE']._serialized_end=571
  _globals['_SLAVESTATUS']._serialized_start=573
  _globals['_SLAVESTATUS']._serialized_end=646
  _globals['_MASTERCOMMAND']._serialized_start=38
  _globals['_MASTERCOMMAND']._serialized_end=207
  _globals['_JOINTCOMMAND']._serialized_start=209
  _globals['_JOINTCOMMAND']._serialized_end=275
  _globals['_SLAVESTATE']._serialized_start=278
  _globals['_SLAVESTATE']._serialized_end=420
  _globals['_JOINTSTATE']._serialized_start=422
  _globals['_JOINTSTATE']._serialized_end=486
  _globals['_ROBOTTELEOPSERVICE']._serialized_start=648
  _globals['_ROBOTTELEOPSERVICE']._serialized_end=744
# @@protoc_insertion_point(module_scope)
